# https://docs.github.com/en/code-security/dependabot/working-with-dependabot/dependabot-options-reference#package-ecosystem-
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
  - package-ecosystem: "pip"
    directory: "/python"
    schedule:
      interval: "weekly"
  - package-ecosystem: "maven"
    directory: "/java"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directories:
      - "/docs"
      - "/nodejs" # /node is deprecated
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directories:
      - "/"
      - "/dockerfiles"
      - "/ci/manylinux_node"
    schedule:
      interval: "weekly"
  - package-ecosystem: "cargo"
    directories:
      - "/"
      - "/nodejs"
      - "/python"
      - "/rust/ffi/node"
      - "/rust/lancedb"
      - "/java/core/lancedb-jni"
    schedule:
      interval: "weekly"
