name: upload-wheel

description: "Upload wheels to Pypi"
inputs:
  fury_token:
    required: true
    description: "release token for the fury repo"

runs:
  using: "composite"
  steps:
  - name: Choose repo
    shell: bash
    id: choose_repo
    run: |
      if [[ ${{ github.ref }} == *beta* ]]; then
        echo "repo=fury" >> $GITHUB_OUTPUT
      else
        echo "repo=pypi" >> $GITHUB_OUTPUT
      fi
  - name: Publish to Fury
    if: steps.choose_repo.outputs.repo == 'fury'
    shell: bash
    env:
      FURY_TOKEN: ${{ inputs.fury_token }}
    run: |
      WHEEL=$(ls target/wheels/lancedb-*.whl 2> /dev/null | head -n 1)
      echo "Uploading $WHEEL to Fury"
      curl -f -F package=@$WHEEL https://$FURY_TOKEN@push.fury.io/lancedb/
  - name: Publish to PyPI
    if: steps.choose_repo.outputs.repo == 'pypi'
    uses: pypa/gh-action-pypi-publish@release/v1
    with:
      packages-dir: target/wheels/
