/* tslint:disable */
/* eslint-disable */
/**
 * LanceDB Vector API
 * LanceDB Cloud API is a RESTful API that allows users to access and modify data stored in LanceDB Cloud. Table actions are considered temporary resource creations and all use POST method. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact@lancedb.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ListTables200Response
 */
export interface ListTables200Response {
    /**
     * 
     * @type {Array<string>}
     * @memberof ListTables200Response
     */
    tables?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof ListTables200Response
     */
    pageToken?: string;
}

/**
 * Check if a given object implements the ListTables200Response interface.
 */
export function instanceOfListTables200Response(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ListTables200ResponseFromJSON(json: any): ListTables200Response {
    return ListTables200ResponseFromJSONTyped(json, false);
}

export function ListTables200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListTables200Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'tables': !exists(json, 'tables') ? undefined : json['tables'],
        'pageToken': !exists(json, 'page_token') ? undefined : json['page_token'],
    };
}

export function ListTables200ResponseToJSON(value?: ListTables200Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'tables': value.tables,
        'page_token': value.pageToken,
    };
}

