/*
 * LanceDB REST Catalog API
 *
 * REST interface for managing LanceDB databases and tables
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateDatabaseRequest {
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "mode")]
    pub mode: Mode,
    #[serde(rename = "options", skip_serializing_if = "Option::is_none")]
    pub options: Option<std::collections::HashMap<String, String>>,
}

impl CreateDatabaseRequest {
    pub fn new(name: String, mode: Mode) -> CreateDatabaseRequest {
        CreateDatabaseRequest {
            name,
            mode,
            options: None,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Mode {
    #[serde(rename = "Create")]
    Create,
    #[serde(rename = "ExistOk")]
    ExistOk,
    #[serde(rename = "Overwrite")]
    Overwrite,
}

impl Default for Mode {
    fn default() -> Mode {
        Self::Create
    }
}

