/*
 * LanceDB REST Catalog API
 *
 * REST interface for managing LanceDB databases and tables
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateTableRequest {
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "definition")]
    pub definition: Box<models::TableDefinition>,
    #[serde(rename = "mode", skip_serializing_if = "Option::is_none")]
    pub mode: Option<Mode>,
}

impl CreateTableRequest {
    pub fn new(name: String, definition: models::TableDefinition) -> CreateTableRequest {
        CreateTableRequest {
            name,
            definition: Box::new(definition),
            mode: None,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Mode {
    #[serde(rename = "Create")]
    Create,
    #[serde(rename = "ExistOk")]
    ExistOk,
    #[serde(rename = "Overwrite")]
    Overwrite,
}

impl Default for Mode {
    fn default() -> Mode {
        Self::Create
    }
}

