/*
 * LanceDB REST Catalog API
 *
 * REST interface for managing LanceDB databases and tables
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DatabaseMetadata {
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "tableCount", skip_serializing_if = "Option::is_none")]
    pub table_count: Option<i32>,
}

impl DatabaseMetadata {
    pub fn new() -> DatabaseMetadata {
        DatabaseMetadata {
            name: None,
            table_count: None,
        }
    }
}

