/* tslint:disable */
/* eslint-disable */
/**
 * LanceDB Vector API
 * LanceDB Cloud API is a RESTful API that allows users to access and modify data stored in LanceDB Cloud. Table actions are considered temporary resource creations and all use POST method. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact@lancedb.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ListTables200Response,
} from '../models';
import {
    ListTables200ResponseFromJSON,
    ListTables200ResponseToJSON,
} from '../models';

export interface CreateTableRequest {
    name: string;
    body: Blob;
}

export interface DropTableRequest {
    name: string;
    body: Blob;
}

export interface ListTablesRequest {
    limit?: number;
    pageToken?: string;
}

/**
 * 
 */
export class TablesApi extends runtime.BaseAPI {

    /**
     * Create a new table
     * Create a new table
     */
    async createTableRaw(requestParameters: CreateTableRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.name === null || requestParameters.name === undefined) {
            throw new runtime.RequiredError('name','Required parameter requestParameters.name was null or undefined when calling createTable.');
        }

        if (requestParameters.body === null || requestParameters.body === undefined) {
            throw new runtime.RequiredError('body','Required parameter requestParameters.body was null or undefined when calling createTable.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/vnd.apache.arrow.stream';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = this.configuration.apiKey("x-api-key"); // key_auth authentication
        }

        const response = await this.request({
            path: `/v1/table/{name}/create/`.replace(`{${"name"}}`, encodeURIComponent(String(requestParameters.name))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters.body as any,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Create a new table
     * Create a new table
     */
    async createTable(requestParameters: CreateTableRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.createTableRaw(requestParameters, initOverrides);
    }

    /**
     * Drop a table
     * Drop a table
     */
    async dropTableRaw(requestParameters: DropTableRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.name === null || requestParameters.name === undefined) {
            throw new runtime.RequiredError('name','Required parameter requestParameters.name was null or undefined when calling dropTable.');
        }

        if (requestParameters.body === null || requestParameters.body === undefined) {
            throw new runtime.RequiredError('body','Required parameter requestParameters.body was null or undefined when calling dropTable.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/vnd.apache.arrow.stream';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = this.configuration.apiKey("x-api-key"); // key_auth authentication
        }

        const response = await this.request({
            path: `/v1/table/{name}/drop/`.replace(`{${"name"}}`, encodeURIComponent(String(requestParameters.name))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters.body as any,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Drop a table
     * Drop a table
     */
    async dropTable(requestParameters: DropTableRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.dropTableRaw(requestParameters, initOverrides);
    }

    /**
     * List tables, optionally, with pagination.
     * List Tables
     */
    async listTablesRaw(requestParameters: ListTablesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListTables200Response>> {
        const queryParameters: any = {};

        if (requestParameters.limit !== undefined) {
            queryParameters['limit'] = requestParameters.limit;
        }

        if (requestParameters.pageToken !== undefined) {
            queryParameters['page_token'] = requestParameters.pageToken;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = this.configuration.apiKey("x-api-key"); // key_auth authentication
        }

        const response = await this.request({
            path: `/v1/table/`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ListTables200ResponseFromJSON(jsonValue));
    }

    /**
     * List tables, optionally, with pagination.
     * List Tables
     */
    async listTables(requestParameters: ListTablesRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListTables200Response> {
        const response = await this.listTablesRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
