# The lance-main branch is a mirror of the LanceDB main branch, where
# the rust dependencies use local paths instead of git.
name: Maintain lance-main branch

on:
  push:
    branches:
      - main

concurrency:
  # only run one job at a time for this workflow
  group: ${{ github.workflow }}

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout commit branch
        uses: actions/checkout@v3
      - name: Checkout lance main branch
        uses: actions/checkout@v3
        with:
          repository: lancedb/lance
      - name: Catch lance-main up to date
        run: |
          git checkout lance-main
          git fetch origin main
          git rebase origin/main --exec "python ci/set_lance_version.py local && git add Cargo.toml Cargo.lock && git commit -m 'use local lance'"
      - name: Push changes to lance-main branch
        run: |
          git push origin lance-main --force
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
