name: NPM Publish

env:
  MACOSX_DEPLOYMENT_TARGET: '10.13'
  CARGO_INCREMENTAL: '1'

permissions:
  contents: write
  id-token: write

on:
  push:
    branches:
      - main
    tags:
      - "v*"
  pull_request:
    # This should trigger a dry run (we skip the final publish step)
    paths:
      - .github/workflows/npm-publish.yml

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  gh-release:
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true
      - name: Extract version
        id: extract_version
        env:
          GITHUB_REF: ${{ github.ref }}
        run: |
          set -e
          echo "Extracting tag and version from $GITHUB_REF"
          if [[ $GITHUB_REF =~ refs/tags/v(.*) ]]; then
            VERSION=${BASH_REMATCH[1]}
            TAG=v$VERSION
            echo "tag=$TAG" >> $GITHUB_OUTPUT
            echo "version=$VERSION" >> $GITHUB_OUTPUT
          else
            echo "Failed to extract version from $GITHUB_REF"
            exit 1
          fi
          echo "Extracted version $VERSION from $GITHUB_REF"
          if [[ $VERSION =~ beta ]]; then
            echo "This is a beta release"

            # Get last release (that is not this one)
            FROM_TAG=$(git tag --sort='version:refname' \
              | grep ^v \
              | grep -vF "$TAG" \
              | python ci/semver_sort.py v \
              | tail -n 1)
          else
            echo "This is a stable release"
            # Get last stable tag (ignore betas)
            FROM_TAG=$(git tag --sort='version:refname' \
              | grep ^v \
              | grep -vF "$TAG" \
              | grep -v beta \
              | python ci/semver_sort.py v \
              | tail -n 1)
          fi
          echo "Found from tag $FROM_TAG"
          echo "from_tag=$FROM_TAG" >> $GITHUB_OUTPUT
      - name: Create Release Notes
        id: release_notes
        uses: mikepenz/release-changelog-builder-action@v4
        with:
          configuration: .github/release_notes.json
          toTag: ${{ steps.extract_version.outputs.tag }}
          fromTag: ${{ steps.extract_version.outputs.from_tag }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Create GH release
        uses: softprops/action-gh-release@v2
        with:
          prerelease: ${{ contains('beta', github.ref) }}
          tag_name: ${{ steps.extract_version.outputs.tag }}
          token: ${{ secrets.GITHUB_TOKEN }}
          generate_release_notes: false
          name: Node/Rust LanceDB v${{ steps.extract_version.outputs.version }}
          body: ${{ steps.release_notes.outputs.changelog }}

  build:
    strategy:
      fail-fast: false
      matrix:
        settings:
          - target: x86_64-apple-darwin
            host: macos-latest
            build: |-
                brew install protobuf
                npm run build-release --target x86_64-apple-darwin
          - target: aarch64-apple-darwin
            host: macos-latest
            build: |-
                brew install protobuf
                npm run build-release --target aarch64-apple-darwin
          - target: x86_64-pc-windows-msvc
            host: windows-latest
            build: |-
                mkdir -p /c/protoc
                curl -L -o /c/protoc/protoc.zip https://github.com/protocolbuffers/protobuf/releases/download/v21.12/protoc-21.12-win64.zip
                unzip /c/protoc/protoc.zip -d /c/protoc
                echo "/c/protoc/bin" >> $GITHUB_PATH
                export PATH="/c/protoc/bin:$PATH"
                protoc --version
                npm run build-release --target x86_64-pc-windows-msvc
          - target: aarch64-pc-windows-msvc
            host: windows-latest
            build: |-
                mkdir -p /c/protoc
                curl -L -o /c/protoc/protoc.zip https://github.com/protocolbuffers/protobuf/releases/download/v21.12/protoc-21.12-win64.zip
                unzip /c/protoc/protoc.zip -d /c/protoc
                export PATH="/c/protoc/bin:$PATH"
                protoc --version
                npm run build-release --target aarch64-pc-windows-msvc
          - target: x86_64-unknown-linux-gnu
            host: ubuntu-latest
            docker: ghcr.io/napi-rs/napi-rs/nodejs-rust:lts-debian
            build: |-
              set -e &&
              apt-get update &&
              apt-get install -y protobuf-compiler libssl-dev &&
              npm run build-release --target x86_64-unknown-linux-gnu
          - target: x86_64-unknown-linux-musl
            host: ubuntu-latest
            docker: ghcr.io/napi-rs/napi-rs/nodejs-rust:lts-alpine
            build: |-
              set -e &&
              apk add protobuf-dev openssl-dev &&
              npm run build-release --target x86_64-unknown-linux-musl
          - target: aarch64-unknown-linux-gnu
            host: ubuntu-latest
            docker: ghcr.io/napi-rs/napi-rs/nodejs-rust:lts-debian-aarch64
            build: |-
              set -e &&
              apt-get update &&
              apt-get install -y protobuf-compiler libssl-dev &&
              rustup target add aarch64-unknown-linux-gnu &&
              npm run build-release --target aarch64-unknown-linux-gnu
          - target: aarch64-unknown-linux-musl
            host: ubuntu-latest
            docker: ghcr.io/napi-rs/napi-rs/nodejs-rust:lts-alpine
            build: |-
              set -e &&
              apk add protobuf-dev openssl-dev &&
              rustup target add aarch64-unknown-linux-musl &&
              npm run build-release --target aarch64-unknown-linux-musl
    name: stable - ${{ matrix.settings.target }} - node@20
    runs-on: ${{ matrix.settings.host }}
    defaults:
      run:
        working-directory: nodejs
    steps:
      - uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        if: ${{ !matrix.settings.docker }}
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: nodejs/package-lock.json
      - name: Install
        uses: dtolnay/rust-toolchain@stable
        if: ${{ !matrix.settings.docker }}
        with:
          toolchain: stable
          targets: ${{ matrix.settings.target }}
      - name: Cache cargo
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            .cargo-cache
            target/
          key: nodejs-${{ matrix.settings.target }}-cargo-${{ matrix.settings.host }}
      - name: Setup toolchain
        run: ${{ matrix.settings.setup }}
        if: ${{ matrix.settings.setup }}
        shell: bash
      - name: Install dependencies
        run: npm ci
      - name: Build in docker
        uses: addnab/docker-run-action@v3
        if: ${{ matrix.settings.docker }}
        with:
          image: ${{ matrix.settings.docker }}
          options: "--user 0:0 -v ${{ github.workspace }}/.cargo-cache/git/db:/usr/local/cargo/git/db \
                    -v ${{ github.workspace }}/.cargo/registry/cache:/usr/local/cargo/registry/cache \
                    -v ${{ github.workspace }}/.cargo/registry/index:/usr/local/cargo/registry/index \
                    -v ${{ github.workspace }}:/build -w /build/nodejs"
          run: ${{ matrix.settings.build }}
      - name: Build
        run: ${{ matrix.settings.build }}
        if: ${{ !matrix.settings.docker }}
        shell: bash
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: bindings-${{ matrix.settings.target }}
          path: lancedb.*.node
          if-no-files-found: error
#   test-macOS-windows-binding:
#     name: Test bindings on ${{ matrix.settings.target }} - node@${{ matrix.node }}
#     needs:
#       - build
#     strategy:
#       fail-fast: false
#       matrix:
#         settings:
#           - host: windows-latest
#             target: x86_64-pc-windows-msvc
#             architecture: x64
#           - host: macos-latest
#             target: aarch64-apple-darwin
#             architecture: arm64
#         node:
#           - '20'
#     runs-on: ${{ matrix.settings.host }}
#     steps:
#       - uses: actions/checkout@v4
#       - name: Setup node
#         uses: actions/setup-node@v4
#         with:
#           node-version: ${{ matrix.node }}
#           cache: npm
#           architecture: ${{ matrix.settings.architecture }}
#       - name: Install dependencies
#         run: npm install
#       - name: Download artifacts
#         uses: actions/download-artifact@v4
#         with:
#           name: bindings-${{ matrix.settings.target }}
#           path: .
#       - name: List packages
#         run: ls -R .
#         shell: bash
#       - name: Test bindings
#         run: npm test
#   test-linux-x64-gnu-binding:
#     name: Test bindings on Linux-x64-gnu - node@${{ matrix.node }}
#     needs:
#       - build
#     strategy:
#       fail-fast: false
#       matrix:
#         settings:
#             - target: x86_64-unknown-linux-gnu
#               host: ubuntu-latest
#             - target: aaarch64-unknown-linux-gnu
#               host: buildjet-16vcpu-ubuntu-2204-arm
#         node:
#           - '20'
#     runs-on: ${{ matrix.settings.host }}
#     steps:
#       - uses: actions/checkout@v4
#       - name: Setup node
#         uses: actions/setup-node@v4
#         with:
#           node-version: ${{ matrix.node }}
#           cache: npm
#       - name: Install dependencies
#         run: npm install
#       - name: Download artifacts
#         uses: actions/download-artifact@v4
#         with:
#           name: bindings-x86_64-unknown-linux-gnu
#           path: .
#       - name: List packages
#         run: ls -R .
#         shell: bash
#       - name: Test bindings
#         run: docker run --rm -v $(pwd):/build -w /build node:${{ matrix.node }}-slim npm test
#   test-linux-x64-musl-binding:
#     name: Test bindings on x86_64-unknown-linux-musl - node@${{ matrix.node }}
#     needs:
#       - build
#     strategy:
#       fail-fast: false
#       matrix:
#         node:
#           - '18'
#           - '20'
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v4
#       - name: Setup node
#         uses: actions/setup-node@v4
#         with:
#           node-version: ${{ matrix.node }}
#           cache: npm
#       - name: Install dependencies
#         run: |
#           npm config set supportedArchitectures.libc "musl"
#           npm install
#       - name: Download artifacts
#         uses: actions/download-artifact@v4
#         with:
#           name: bindings-x86_64-unknown-linux-musl
#           path: .
#       - name: List packages
#         run: ls -R .
#         shell: bash
#       - name: Test bindings
#         run: docker run --rm -v $(pwd):/build -w /build node:${{ matrix.node }}-alpine npm test
#   test-linux-aarch64-gnu-binding:
#     name: Test bindings on aarch64-unknown-linux-gnu - node@${{ matrix.node }}
#     needs:
#       - build
#     strategy:
#       fail-fast: false
#       matrix:
#         node:
#           - '18'
#           - '20'
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v4
#       - name: Download artifacts
#         uses: actions/download-artifact@v4
#         with:
#           name: bindings-aarch64-unknown-linux-gnu
#           path: .
#       - name: List packages
#         run: ls -R .
#         shell: bash
#       - name: Install dependencies
#         run: |
#           npm config set supportedArchitectures.cpu "arm64"
#           npm config set supportedArchitectures.libc "glibc"
#           npm install
#       - name: Set up QEMU
#         uses: docker/setup-qemu-action@v3
#         with:
#           platforms: arm64
#       - run: docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
#       - name: Setup and run tests
#         uses: addnab/docker-run-action@v3
#         with:
#           image: node:${{ matrix.node }}-slim
#           options: '--platform linux/arm64 -v ${{ github.workspace }}:/build -w /build'
#           run: |
#             set -e
#             npm test
#             ls -la
#   test-linux-aarch64-musl-binding:
#     name: Test bindings on aarch64-unknown-linux-musl - node@lts
#     needs:
#       - build
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v4
#       - name: Download artifacts
#         uses: actions/download-artifact@v4
#         with:
#           name: bindings-aarch64-unknown-linux-musl
#           path: .
#       - name: List packages
#         run: ls -R .
#         shell: bash
#       - name: Install dependencies
#         run: |
#           npm config set supportedArchitectures.cpu "arm64"
#           npm config set supportedArchitectures.libc "musl"
#           npm install
#       - name: Set up QEMU
#         uses: docker/setup-qemu-action@v3
#         with:
#           platforms: arm64
#       - run: docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
#       - name: Setup and run tests
#         uses: addnab/docker-run-action@v3
#         with:
#           image: node:lts-alpine
#           options: '--platform linux/arm64 -v ${{ github.workspace }}:/build -w /build'
#           run: |
#             set -e
#             npm test
#   test-linux-arm-gnueabihf-binding:
#     name: Test bindings on armv7-unknown-linux-gnueabihf - node@${{ matrix.node }}
#     needs:
#       - build
#     strategy:
#       fail-fast: false
#       matrix:
#         node:
#           - '18'
#           - '20'
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v4
#       - name: Download artifacts
#         uses: actions/download-artifact@v4
#         with:
#           name: bindings-armv7-unknown-linux-gnueabihf
#           path: .
#       - name: List packages
#         run: ls -R .
#         shell: bash
#       - name: Install dependencies
#         run: |
#           npm config set supportedArchitectures.cpu "arm"
#           npm install
#       - name: Set up QEMU
#         uses: docker/setup-qemu-action@v3
#         with:
#           platforms: arm
#       - run: docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
#       - name: Setup and run tests
#         uses: addnab/docker-run-action@v3
#         with:
#           image: node:${{ matrix.node }}-bullseye-slim
#           options: '--platform linux/arm/v7 -v ${{ github.workspace }}:/build -w /build'
#           run: |
#             set -e
#             npm test
#             ls -la
#   publish:
#     name: Publish
#     runs-on: ubuntu-latest
#     needs:
#       - build-freebsd
#       - test-macOS-windows-binding
#       - test-linux-x64-gnu-binding
#       - test-linux-x64-musl-binding
#       - test-linux-aarch64-gnu-binding
#       - test-linux-aarch64-musl-binding
#       - test-linux-arm-gnueabihf-binding
#     steps:
#       - uses: actions/checkout@v4
#       - name: Setup node
#         uses: actions/setup-node@v4
#         with:
#           node-version: 20
#           cache: npm
#       - name: Install dependencies
#         run: npm install
#       - name: Download all artifacts
#         uses: actions/download-artifact@v4
#         with:
#           path: artifacts
#       - name: Move artifacts
#         run: npm artifacts
#       - name: List packages
#         run: ls -R ./npm
#         shell: bash
#       - name: Publish
#         run: |
#           npm config set provenance true
#           if git log -1 --pretty=%B | grep "^[0-9]\+\.[0-9]\+\.[0-9]\+$";
#           then
#             echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
#             npm publish --access public
#           elif git log -1 --pretty=%B | grep "^[0-9]\+\.[0-9]\+\.[0-9]\+";
#           then
#             echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
#             npm publish --tag next --access public
#           else
#             echo "Not a release, skipping publish"
#           fi
#         env:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#           NPM_TOKEN: ${{ secrets.NPM_TOKEN }}


  # ----------------------------------------------------------------------------
  # vectordb release (legacy)
  # ----------------------------------------------------------------------------
  # TODO: delete this when we drop vectordb
  node:
    name: vectordb Typescript
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: node
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: "npm"
          cache-dependency-path: node/package-lock.json
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y protobuf-compiler libssl-dev
      - name: Build
        run: |
          npm ci
          npm run tsc
          npm pack
      - name: Upload Linux Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: node-package
          path: |
            node/vectordb-*.tgz

  node-macos:
    name: vectordb ${{ matrix.config.arch }}
    strategy:
      matrix:
        config:
          - arch: x86_64-apple-darwin
            runner: macos-13
          - arch: aarch64-apple-darwin
            # xlarge is implicitly arm64.
            runner: macos-14
    runs-on: ${{ matrix.config.runner }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install system dependencies
        run: brew install protobuf
      - name: Install npm dependencies
        run: |
          cd node
          npm ci
      - name: Build MacOS native node modules
        run: bash ci/build_macos_artifacts.sh ${{ matrix.config.arch }}
      - name: Upload Darwin Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: node-native-darwin-${{ matrix.config.arch }}
          path: |
            node/dist/lancedb-vectordb-darwin*.tgz

  node-linux-gnu:
    name: vectordb (${{ matrix.config.arch}}-unknown-linux-gnu)
    runs-on: ${{ matrix.config.runner }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - arch: x86_64
            runner: ubuntu-latest
          - arch: aarch64
            # For successful fat LTO builds, we need a large runner to avoid OOM errors.
            runner: warp-ubuntu-latest-arm64-4x
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # To avoid OOM errors on ARM, we create a swap file.
      - name: Configure aarch64 build
        if: ${{ matrix.config.arch == 'aarch64' }}
        run: |
          free -h
          sudo fallocate -l 16G /swapfile
          sudo chmod 600 /swapfile
          sudo mkswap /swapfile
          sudo swapon /swapfile
          echo "/swapfile swap swap defaults 0 0" >> sudo /etc/fstab
          # print info
          swapon --show
          free -h
      - name: Build Linux Artifacts
        run: |
          bash ci/build_linux_artifacts.sh ${{ matrix.config.arch }} ${{ matrix.config.arch }}-unknown-linux-gnu
      - name: Upload Linux Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: node-native-linux-${{ matrix.config.arch }}-gnu
          path: |
            node/dist/lancedb-vectordb-linux*.tgz

  node-windows:
    name: vectordb ${{ matrix.target }}
    runs-on: windows-2022
    strategy:
      fail-fast: false
      matrix:
        target: [x86_64-pc-windows-msvc]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Protoc v21.12
        working-directory: C:\
        run: |
          New-Item -Path 'C:\protoc' -ItemType Directory
          Set-Location C:\protoc
          Invoke-WebRequest https://github.com/protocolbuffers/protobuf/releases/download/v21.12/protoc-21.12-win64.zip -OutFile C:\protoc\protoc.zip
          7z x protoc.zip
          Add-Content $env:GITHUB_PATH "C:\protoc\bin"
        shell: powershell
      - name: Install npm dependencies
        run: |
          cd node
          npm ci
      - name: Build Windows native node modules
        run: .\ci\build_windows_artifacts.ps1 ${{ matrix.target }}
      - name: Upload Windows Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: node-native-windows
          path: |
            node/dist/lancedb-vectordb-win32*.tgz

  release:
    name: vectordb NPM Publish
    needs: [node, node-macos, node-linux-gnu, node-windows]
    runs-on: ubuntu-latest
    # Only runs on tags that matches the make-release action
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - uses: actions/download-artifact@v4
        with:
          pattern: node-*
      - name: Display structure of downloaded files
        run: ls -R
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          registry-url: "https://registry.npmjs.org"
      - name: Publish to NPM
        env:
          NODE_AUTH_TOKEN: ${{ secrets.LANCEDB_NPM_REGISTRY_TOKEN }}
        run: |
          # Tag beta as "preview" instead of default "latest". See lancedb
          # npm publish step for more info.
          if [[ $GITHUB_REF =~ refs/tags/v(.*)-beta.* ]]; then
            PUBLISH_ARGS="--tag preview"
          fi

          mv */*.tgz .
          for filename in *.tgz; do
            npm publish $PUBLISH_ARGS $filename
          done
      - name: Notify Slack Action
        uses: ravsamhq/notify-slack-action@2.3.0
        if: ${{ always() }}
        with:
          status: ${{ job.status }}
          notify_when: "failure"
          notification_title: "{workflow} is failing"
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.ACTION_MONITORING_SLACK }}

  update-package-lock:
    if: startsWith(github.ref, 'refs/tags/v')
    needs: [release]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: main
          token: ${{ secrets.LANCEDB_RELEASE_TOKEN }}
          fetch-depth: 0
          lfs: true
      - uses: ./.github/workflows/update_package_lock
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
