name: Typo checker
on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  run:
    name: Spell Check with Typos
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v6

      - name: Check spelling of the entire repository
        uses: crate-ci/typos@6802cc60d4e7f78b9d5454f6cf3935c042d5e1e3 # v1.26.0
